exclude: "docs|.git"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Can run individually with `pre-commit run isort --all-files`
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # Can run individually with `flynt [file]` or `flynt [source]`
  - repo: https://github.com/ikamensh/flynt
    rev: '1.0.1'
    hooks:
      - id: flynt
        args: ["--fail-on-change", "--verbose"]
        require_serial: true

  # Can run individually with `pre-commit run flake8 --all-files`
  # Need to use flake8 GitHub mirror due to CentOS git issue with GitLab
  # https://github.com/pre-commit/pre-commit/issues/1206
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]

  # Can run individually with `pre-commit run mypy --all-files`
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ["--config=setup.cfg", "--show-error-codes"]
        verbose: true
        additional_dependencies: ['types-requests']

# https://pre-commit.ci/#configuration
ci:
  autofix_prs: false
  autoupdate_schedule: monthly
