omega:
  run_modes:
    config_ocean_run_mode: forward
  time_management:
    config_run_duration: {{ run_duration }}
  decomposition:
    config_block_decomp_file_prefix: graph.info.part.
  advection:
    config_vert_coord_movement: impermeable_interfaces
  time_integration:
    config_dt: {{ dt }}
    config_time_integrator: {{ time_integrator }}
  debug:
    config_disable_thick_sflux: true
    config_disable_vel_all_tend: true
    config_disable_vel_coriolis: true
    config_disable_vel_pgrad: true
    config_disable_vel_hmix: true
    config_disable_vel_surface_stress: true
    config_disable_vel_explicit_bottom_drag: true
    config_disable_vel_vmix: true
    config_disable_vel_vadv: true
    config_disable_tr_hmix: true
    config_disable_tr_vmix: true
    config_disable_tr_sflux: true
    config_disable_tr_nonlocalflux: true
    config_check_ssh_consistency: false
  cvmix:
    config_use_cvmix: false
  eos:
    config_eos_type: linear
  tracer_forcing_debugTracers:
    config_use_debugTracers: true
  streams:
    mesh:
      filename_template: init.nc
    input:
      filename_template: init.nc
    restart:
      output_interval: 0030_00:00:00
    output:
      type: output
      filename_template: output.nc
      output_interval: {{ output_interval }}
      clobber_mode: truncate
      reference_time: 0001-01-01_00:00:00
      contents:
      - tracers
      - mesh
      - xtime
      - normalVelocity
      - layerThickness
      - refZMid
      - refLayerThickness
      - kineticEnergyCell
      - relativeVorticityCell
