mpas-ocean:
  time_management:
    config_run_duration: 0010_00:00:00
  tracer_forcing_activeTracers:
    config_use_activeTracers_surface_bulk_forcing: false
    config_use_activeTracers_surface_restoring: false
    config_use_activeTracers_interior_restoring: false
  bottom_drag:
    config_implicit_constant_bottom_drag_coeff: 0.0
  cvmix:
    config_use_cvmix: false
