ocean:
  time_management:
    config_stop_time: none
    config_run_duration: {{ run_duration }}
  time_integration:
    config_dt: {{ dt }}
  forcing:
    config_use_bulk_wind_stress: true

mpas-ocean:
  streams:
    mesh:
      filename_template: init.nc
    input:
      filename_template: init.nc
    forcing:
      filename_template: init.nc
      input_interval: initial_only
      type: input
      contents:
      - windStressZonal
      - windStressMeridional
    restart:
      output_interval: {{ run_duration }}
    output:
      type: output
      filename_template: output.nc
      output_interval: {{ output_interval }}
      clobber_mode: truncate
      reference_time: 0001-01-01_00:00:00
      contents:
      - tracers
      - xtime
      - normalVelocity
      - layerThickness
      - kineticEnergyCell
      - relativeVorticityCell

Omega:
  TimeIntegration:
    TimeStepper: RungeKutta4
  Tendencies:
    PressureGradTendencyEnable : false
  Tracers:
    Debug: []
  IOStreams:
    InitialVertCoord:
      Filename: init.nc
    InitialState:
      Filename: init.nc
      Contents:
        - State
        - Tracers
        - WindStressZonal
        - WindStressMeridional
    History:
      Filename: output.nc
      Freq: {{ output_freq }}
      FreqUnits: {{ output_freq_units }}
      IfExists: append
      # effectively never
      FileFreq: 9999
      FileFreqUnits: years
      Contents:
        - State
        - AuxiliaryState
        - Tracers
        - PseudoThickness
        - SshCell
        - KineticEnergyCell
        - Eos
