ocean:
  time_management:
    config_stop_time: none
    config_run_duration: {{ run_duration }}
  time_integration:
    config_dt: {{ dt }}
    config_time_integrator: {{ time_integrator }}

mpas-ocean:
  run_modes:
    config_ocean_run_mode: forward
  decomposition:
    config_block_decomp_file_prefix: graph.info.part.
  cvmix:
    config_use_cvmix: false
  ALE_vertical_grid:
    config_vert_coord_movement : fixed
  debug:
    config_disable_thick_all_tend: true
    config_disable_vel_all_tend: true
    config_disable_tr_hmix: true
    config_disable_tr_vmix: true
    config_disable_tr_sflux: true
    config_disable_tr_nonlocalflux: true
    config_check_ssh_consistency: false
    #config_disable_tr_all_tend: false
  eos:
    config_eos_type: linear
  forcing:
    config_use_bulk_wind_stress: false
    config_use_bulk_thickness_flux: false
  advection:
    config_vert_tracer_adv_flux_order: 2
    config_horiz_tracer_adv_order: 2
    config_flux_limiter: none
  tracer_forcing_activeTracers:
    config_use_activeTracers_surface_restoring: false
    config_use_activeTracers_interior_restoring: false
    config_use_activeTracers: true
    config_use_activeTracers_surface_bulk_forcing: false
  tracer_forcing_debugTracers:
    config_use_debugTracers: true
  AM_mixedLayerDepths:
    config_AM_mixedLayerDepths_enable: false
  streams:
    mesh:
      filename_template: init.nc
    input:
      filename_template: init.nc
    restart: {}
    output:
      type: output
      filename_template: output.nc
      output_interval: {{ output_interval }}
      clobber_mode: truncate
      reference_time: 0001-01-01_00:00:00
      contents:
      - tracers
      - mesh
      - xtime
      - normalVelocity
      - layerThickness
      - refZMid
      - refLayerThickness
      - kineticEnergyCell
      - relativeVorticityCell
      - velocityX
      - vertVelocityTop
