ocean:
  hmix_del2:
    config_use_mom_del2: false
    config_use_tracer_del2: false
  hmix_del4:
    config_use_mom_del4: false
    config_use_tracer_del4: false
  cvmix:
    config_cvmix_background_diffusion: 1.e-5
    config_cvmix_background_viscosity: 1.e-4
    config_cvmix_num_ri_smooth_loops: 2
  eos:
    config_eos_type: linear
  eos_linear:
    config_eos_linear_alpha: 0.2
    config_eos_linear_beta: 0.01
    # 1000.0 + 0.2 * 5 - 0.01 * 35
    config_eos_linear_densityref: 1000.65
  debug:
    config_disable_tr_sflux: false
    config_disable_thick_sflux: false
    config_disable_thick_hadv: true
    config_disable_thick_vadv: true
    config_disable_vel_vmix: true
    config_disable_vel_pgrad: true
    config_disable_vel_explicit_bottom_drag: true
    config_disable_vel_vadv: true
    config_disable_tr_adv: true
    config_disable_tr_vmix: true

Omega:
  Tendencies:
    TracerVertAdvTendencyEnable: false
  IOStreams:
    History:
      Filename: output.nc
      Freq: {{ output_freq }}
      FreqUnits: Seconds
      IfExists: append
      # effectively never
      FileFreq: 9999
      FileFreqUnits: years
      Contents:
      - AuxiliaryState
      - State
      - GeomZMid
      - Tracers
      - SshCell
      - Eos
      - Forcing
    Forcing:
      UsePointerFile: false
      Filename: forcing.nc
      Mode: read
      Precision: double
      Freq: 1
      FreqUnits: OnStartup
      UseStartEnd: false
      Contents:
      - Forcing
    ShortwaveExtinctionIn:
      UsePointerFile: false
      Filename: shortwave_extinction_coeffs.nc
      Mode: read
      Precision: double
      Freq: 1
      FreqUnits: OnStartup
      UseStartEnd: false
      Contents:
      - ShortwaveExtinction
