mpas-ocean:
  time_management:
    config_stop_time: none
    config_run_duration: 0000_00:12:00
  time_integration:
    config_dt: 0000_00:01:00
    config_time_integrator: split_explicit
  io:
    config_write_output_on_startup: false
  hmix_del2:
    config_use_mom_del2: true
    config_mom_del2: 1.0e3
  bottom_drag:
    config_implicit_bottom_drag_type: constant
    config_implicit_constant_bottom_drag_coeff: 0.01
  cvmix:
    config_cvmix_background_scheme: none
    config_use_cvmix_convection: true
  split_explicit_ts:
    config_btr_dt: 00:00:09
  streams:
    mesh:
      filename_template: init.nc
    input:
      filename_template: init.nc
    restart: {}
    output:
      type: output
      filename_template: output.nc
      output_interval: 0000_00:00:01
      clobber_mode: truncate
      contents:
      - tracers
      - xtime
      - normalVelocity
      - layerThickness
      - ssh
      - vertVelocityTop
